name: ost
favicon: null
layout_spectrum: 0.49827949702739716
typography_spectrum: 0.1356684654019773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
